---
#--- Init ---#
- name: Stop service postgresql, if running
  become: yes
  command: "systemctl stop postgresql-{{ postgresql_version }}"
  # For "Failed to stop postgresql-12.service: Unit postgresql-12.service not loaded." error.
  ignore_errors: yes

- name: PostgreSQL data directory exist?
  become: yes
  stat:
    path: "{{ postgresql_data_path }}"
  register: is_postgresql_data

- name: Delete PostgreSQL data directory if exist
  become: yes
  file:
    path: "{{ postgresql_data_path }}"
    state: absent
  when: is_postgresql_data.stat.exists

#--- Installation PostgreSQL ---#
# Installation Steps: https://www.postgresql.org/download/linux/redhat/
- name: Install PostgreSQL repo
  become: yes
  dnf:
    name: "{{ postgresql_repo }}"

- name: Disable the built-in PostgreSQL module
  become: yes
  command: "dnf -qy module disable postgresql"

- name: Install the client packages
  become: yes
  dnf:
    name: "postgresql{{ postgresql_version }}"

- name: Optionally install the server packages
  become: yes
  dnf:
    name: "postgresql{{ postgresql_version }}-server"

- name: Optionally initialize the database and enable automatic start
  become: yes
  command: "{{ item }}"
  loop:
    - /usr/pgsql-{{ postgresql_version }}/bin/postgresql-{{ postgresql_version }}-setup initdb
    - systemctl enable postgresql-{{ postgresql_version }}
    - systemctl start postgresql-{{ postgresql_version }}
  # For "Data directory is not empty!" error.
  ignore_errors: yes

#--- Dependency Packages ---#
- name: Install python3-psycopg2 for PostgreSQL database adapter
  become: yes
  dnf:
    name: python3-psycopg2

- name: Install postgresql-devel
  become: yes
  dnf:
    name: postgresql-devel

#--- Setting ---#
- name: Activate User postgres in CentOS (add password)
  become: yes
  user:
    name: "postgres"
    password: "{{ 'postgres' | password_hash('sha256') }}"

- name: Create PostgreSQL User({{ postgresql_username }})
  # It need "become: yes" for "become: postgres".
  become: yes
  become_user: postgres
  postgresql_user:
    name: "{{ postgresql_username }}"
    password: "{{ postgresql_password }}"
    role_attr_flags: SUPERUSER,CREATEDB,REPLICATION
    login_user: postgres

- name: Copy postgresql.conf
  become: yes
  copy:
    src: "../files/postgresql.conf"
    dest: "/var/lib/pgsql/12/data/"

- name: Copy pg_hba.conf
  become: yes
  copy:
    src: "../files/pg_hba.conf"
    dest: "/var/lib/pgsql/12/data/"
