---
#--- Setup ---#
- name: Install Yarn repo
  become: yes
  get_url:
    url: "{{ yarn_repo }}"
    dest: "{{ yarn_dest }}"
  # It instead of "curl --silent --location https://dl.yarnpkg.com/rpm/yarn.repo | sudo tee /etc/yum.repos.d/yarn.repo".

- name: Install Yarn
  become: yes
  dnf:
    name:
      - yarn

- name: Install Node.js
  become: yes
  dnf:
    name:
      - nodejs

- name: Set bundle installation path
  command: "bundle config set path 'vendor/bundle'"

- name: Import Rails new SQLite tasks
  import_tasks: rails-new-sqlite.yml

- name: Import Rails new PostgreSQL tasks
  import_tasks: rails-new-postgresql.yml

- name: Import Rails Miniest tasks
  import_tasks: minitest.yml
