---
- name: Install Yarn repo
  become: yes
  get_url:
    url: "{{ yarn_repo }}"
    dest: "{{ yarn_dest }}"
  # shell: "curl --silent --location https://dl.yarnpkg.com/rpm/yarn.repo | sudo tee /etc/yum.repos.d/yarn.repo"

- name: Install Yarn
  become: yes
  dnf:
    name:
      - yarn

- name: Install Node.js
  become: yes
  dnf:
    name:
      - nodejs
