---
#--- Set up ---#
- name: Install Yarn repo
  become: yes
  get_url:
    url: "{{ yarn_repo }}"
    dest: "{{ yarn_dest }}"
  # shell: "curl --silent --location https://dl.yarnpkg.com/rpm/yarn.repo | sudo tee /etc/yum.repos.d/yarn.repo"

- name: Install Yarn
  become: yes
  dnf:
    name:
      - yarn

- name: Install Node.js
  become: yes
  dnf:
    name:
      - nodejs

#--- Rails ---#
- name: Set bundle installation path
  shell: "bundle config set path 'vendor/bundle'"

- name: Create sample Rails directory
  file:
    path: "{{ sample_rails_path }}"
    state: directory

- name: Copy Gemfile
  copy:
    src: "../files/Gemfile"
    dest: "{{ sample_rails_path }}"

- name: Install RubyGems
  bundler:
      state: present
  args:
    chdir: "{{ sample_rails_path }}"

- name: Rails new
  expect:
    command: "bundle exec rails new ."
    responses:
      (.*)Overwrite (.*)Gemfile(.*): "Y"
    # timeout 1200 sec = 20 min
    timeout: 1200
  args:
    chdir: "{{ sample_rails_path }}"
