---
# - name: Upgrade all packages
#   become: yes
#   dnf:
#     name: "*"
#     state: latest

- name: Copy .bashrc
  copy:
    src: "../files/.bashrc"
    dest: "{{ bashrc }}"

- name: Source .bashrc
  shell: ". {{ bashrc }}"

- name: Install fish shell repo
  become: yes
  get_url:
    url: "{{ fish_repo }}"
    dest: "{{ fish_dest }}"

- name: Install fish shell
  become: yes
  dnf:
    name: fish
