---
- name: Install packages for Ruby
  become: yes
  dnf:
    name:
      - wget
      - git-all
      - openssl-devel
      - readline-devel
      - sqlite
      - sqlite-devel
      - gcc
      - gcc-c++
      - make

- name: Git clone rbenv
  git:
    repo: "{{ rbenv_repo }}"
    dest: "{{ rbenv_root }}"

- name: Git clone ruby-build
  git:
    repo: "{{ ruby_build_repo }}"
    dest: "{{ ruby_build_root }}"

# Run following tasks at common tasks
# (1) Copy .bashrc
# (2) Source .bashrc

- name: Check installed ruby version
  command: "rbenv versions"
  register: "installed_ruby_version"
  ignore_errors: yes

- name: Install Ruby {{ ruby_version }}
  command: "rbenv install {{ ruby_version }}"
  when: installed_ruby_version.stdout.find(ruby_version) == -1
# Conditional statements (= when) should not include jinja2 templating delimiters such as {{ }} or {% %}.

- name: Set Ruby version {{ ruby_version }}
  command: "rbenv global {{ ruby_version }}"
  when: installed_ruby_version.stdout.find(ruby_version) == -1

- name: Rehash rbenv
  command: "rbenv rehash {{ ruby_version }}"

- name: Install bundler
  gem:
    name: bundler
